import "./globals.css";
import Header from '@/components/layout/header/Header'
import { Footer } from '../components/layout/footer/Footer'
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Toaster position="top-right" richColors />
        {children}
        <Footer />
      </body>
    </html>
  );
}
